// Generated by gencpp from file lab3/ChargeFeedback.msg
// DO NOT EDIT!


#ifndef LAB3_MESSAGE_CHARGEFEEDBACK_H
#define LAB3_MESSAGE_CHARGEFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lab3
{
template <class ContainerAllocator>
struct ChargeFeedback_
{
  typedef ChargeFeedback_<ContainerAllocator> Type;

  ChargeFeedback_()
    : battery(0)  {
    }
  ChargeFeedback_(const ContainerAllocator& _alloc)
    : battery(0)  {
  (void)_alloc;
    }



   typedef int32_t _battery_type;
  _battery_type battery;





  typedef boost::shared_ptr< ::lab3::ChargeFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lab3::ChargeFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct ChargeFeedback_

typedef ::lab3::ChargeFeedback_<std::allocator<void> > ChargeFeedback;

typedef boost::shared_ptr< ::lab3::ChargeFeedback > ChargeFeedbackPtr;
typedef boost::shared_ptr< ::lab3::ChargeFeedback const> ChargeFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lab3::ChargeFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lab3::ChargeFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lab3::ChargeFeedback_<ContainerAllocator1> & lhs, const ::lab3::ChargeFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.battery == rhs.battery;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lab3::ChargeFeedback_<ContainerAllocator1> & lhs, const ::lab3::ChargeFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lab3

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lab3::ChargeFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lab3::ChargeFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lab3::ChargeFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lab3::ChargeFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab3::ChargeFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab3::ChargeFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lab3::ChargeFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "295e87f732e03ed6443766199f72b602";
  }

  static const char* value(const ::lab3::ChargeFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x295e87f732e03ed6ULL;
  static const uint64_t static_value2 = 0x443766199f72b602ULL;
};

template<class ContainerAllocator>
struct DataType< ::lab3::ChargeFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lab3/ChargeFeedback";
  }

  static const char* value(const ::lab3::ChargeFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lab3::ChargeFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define the feedback - current battery\n"
"int32 battery\n"
"\n"
;
  }

  static const char* value(const ::lab3::ChargeFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lab3::ChargeFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.battery);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ChargeFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lab3::ChargeFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lab3::ChargeFeedback_<ContainerAllocator>& v)
  {
    s << indent << "battery: ";
    Printer<int32_t>::stream(s, indent + "  ", v.battery);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LAB3_MESSAGE_CHARGEFEEDBACK_H
