// Generated by gencpp from file lab3/ChargeGoal.msg
// DO NOT EDIT!


#ifndef LAB3_MESSAGE_CHARGEGOAL_H
#define LAB3_MESSAGE_CHARGEGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lab3
{
template <class ContainerAllocator>
struct ChargeGoal_
{
  typedef ChargeGoal_<ContainerAllocator> Type;

  ChargeGoal_()
    : goal(0)  {
    }
  ChargeGoal_(const ContainerAllocator& _alloc)
    : goal(0)  {
  (void)_alloc;
    }



   typedef int32_t _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::lab3::ChargeGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lab3::ChargeGoal_<ContainerAllocator> const> ConstPtr;

}; // struct ChargeGoal_

typedef ::lab3::ChargeGoal_<std::allocator<void> > ChargeGoal;

typedef boost::shared_ptr< ::lab3::ChargeGoal > ChargeGoalPtr;
typedef boost::shared_ptr< ::lab3::ChargeGoal const> ChargeGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lab3::ChargeGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lab3::ChargeGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lab3::ChargeGoal_<ContainerAllocator1> & lhs, const ::lab3::ChargeGoal_<ContainerAllocator2> & rhs)
{
  return lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lab3::ChargeGoal_<ContainerAllocator1> & lhs, const ::lab3::ChargeGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lab3

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lab3::ChargeGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lab3::ChargeGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lab3::ChargeGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lab3::ChargeGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab3::ChargeGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab3::ChargeGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lab3::ChargeGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "18df0149936b7aa95588e3862476ebde";
  }

  static const char* value(const ::lab3::ChargeGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x18df0149936b7aa9ULL;
  static const uint64_t static_value2 = 0x5588e3862476ebdeULL;
};

template<class ContainerAllocator>
struct DataType< ::lab3::ChargeGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lab3/ChargeGoal";
  }

  static const char* value(const ::lab3::ChargeGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lab3::ChargeGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define the charge goal\n"
"int32 goal\n"
;
  }

  static const char* value(const ::lab3::ChargeGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lab3::ChargeGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ChargeGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lab3::ChargeGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lab3::ChargeGoal_<ContainerAllocator>& v)
  {
    s << indent << "goal: ";
    Printer<int32_t>::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LAB3_MESSAGE_CHARGEGOAL_H
