(cl:defpackage lab3-msg
  (:use )
  (:export
   "<CHARGEACTION>"
   "CHARGEACTION"
   "<CHARGEACTIONFEEDBACK>"
   "CHARGEACTIONFEEDBACK"
   "<CHARGEACTIONGOAL>"
   "CHARGEACTIONGOAL"
   "<CHARGEACTIONRESULT>"
   "CHARGEACTIONRESULT"
   "<CHARGEFEEDBACK>"
   "CHARGEFEEDBACK"
   "<CHARGEGOAL>"
   "CHARGEGOAL"
   "<CHARGERESULT>"
   "CHARGERESULT"
  ))

