; Auto-generated. Do not edit!


(cl:in-package lab3-msg)


;//! \htmlinclude ChargeFeedback.msg.html

(cl:defclass <ChargeFeedback> (roslisp-msg-protocol:ros-message)
  ((battery
    :reader battery
    :initarg :battery
    :type cl:integer
    :initform 0))
)

(cl:defclass ChargeFeedback (<ChargeFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ChargeFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ChargeFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name lab3-msg:<ChargeFeedback> is deprecated: use lab3-msg:ChargeFeedback instead.")))

(cl:ensure-generic-function 'battery-val :lambda-list '(m))
(cl:defmethod battery-val ((m <ChargeFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader lab3-msg:battery-val is deprecated.  Use lab3-msg:battery instead.")
  (battery m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ChargeFeedback>) ostream)
  "Serializes a message object of type '<ChargeFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'battery)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ChargeFeedback>) istream)
  "Deserializes a message object of type '<ChargeFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'battery) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ChargeFeedback>)))
  "Returns string type for a message object of type '<ChargeFeedback>"
  "lab3/ChargeFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ChargeFeedback)))
  "Returns string type for a message object of type 'ChargeFeedback"
  "lab3/ChargeFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ChargeFeedback>)))
  "Returns md5sum for a message object of type '<ChargeFeedback>"
  "295e87f732e03ed6443766199f72b602")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ChargeFeedback)))
  "Returns md5sum for a message object of type 'ChargeFeedback"
  "295e87f732e03ed6443766199f72b602")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ChargeFeedback>)))
  "Returns full string definition for message of type '<ChargeFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the feedback - current battery~%int32 battery~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ChargeFeedback)))
  "Returns full string definition for message of type 'ChargeFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the feedback - current battery~%int32 battery~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ChargeFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ChargeFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ChargeFeedback
    (cl:cons ':battery (battery msg))
))
