; Auto-generated. Do not edit!


(cl:in-package lab3-msg)


;//! \htmlinclude ChargeGoal.msg.html

(cl:defclass <ChargeGoal> (roslisp-msg-protocol:ros-message)
  ((goal
    :reader goal
    :initarg :goal
    :type cl:integer
    :initform 0))
)

(cl:defclass ChargeGoal (<ChargeGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ChargeGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ChargeGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name lab3-msg:<ChargeGoal> is deprecated: use lab3-msg:ChargeGoal instead.")))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <ChargeGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader lab3-msg:goal-val is deprecated.  Use lab3-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ChargeGoal>) ostream)
  "Serializes a message object of type '<ChargeGoal>"
  (cl:let* ((signed (cl:slot-value msg 'goal)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ChargeGoal>) istream)
  "Deserializes a message object of type '<ChargeGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'goal) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ChargeGoal>)))
  "Returns string type for a message object of type '<ChargeGoal>"
  "lab3/ChargeGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ChargeGoal)))
  "Returns string type for a message object of type 'ChargeGoal"
  "lab3/ChargeGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ChargeGoal>)))
  "Returns md5sum for a message object of type '<ChargeGoal>"
  "18df0149936b7aa95588e3862476ebde")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ChargeGoal)))
  "Returns md5sum for a message object of type 'ChargeGoal"
  "18df0149936b7aa95588e3862476ebde")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ChargeGoal>)))
  "Returns full string definition for message of type '<ChargeGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the charge goal~%int32 goal~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ChargeGoal)))
  "Returns full string definition for message of type 'ChargeGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the charge goal~%int32 goal~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ChargeGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ChargeGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'ChargeGoal
    (cl:cons ':goal (goal msg))
))
