; Auto-generated. Do not edit!


(cl:in-package lab3-msg)


;//! \htmlinclude ChargeResult.msg.html

(cl:defclass <ChargeResult> (roslisp-msg-protocol:ros-message)
  ((result
    :reader result
    :initarg :result
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass ChargeResult (<ChargeResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ChargeResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ChargeResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name lab3-msg:<ChargeResult> is deprecated: use lab3-msg:ChargeResult instead.")))

(cl:ensure-generic-function 'result-val :lambda-list '(m))
(cl:defmethod result-val ((m <ChargeResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader lab3-msg:result-val is deprecated.  Use lab3-msg:result instead.")
  (result m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ChargeResult>) ostream)
  "Serializes a message object of type '<ChargeResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'result) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ChargeResult>) istream)
  "Deserializes a message object of type '<ChargeResult>"
    (cl:setf (cl:slot-value msg 'result) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ChargeResult>)))
  "Returns string type for a message object of type '<ChargeResult>"
  "lab3/ChargeResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ChargeResult)))
  "Returns string type for a message object of type 'ChargeResult"
  "lab3/ChargeResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ChargeResult>)))
  "Returns md5sum for a message object of type '<ChargeResult>"
  "eb13ac1f1354ccecb7941ee8fa2192e8")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ChargeResult)))
  "Returns md5sum for a message object of type 'ChargeResult"
  "eb13ac1f1354ccecb7941ee8fa2192e8")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ChargeResult>)))
  "Returns full string definition for message of type '<ChargeResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%bool result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ChargeResult)))
  "Returns full string definition for message of type 'ChargeResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Result~%bool result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ChargeResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ChargeResult>))
  "Converts a ROS message object to a list"
  (cl:list 'ChargeResult
    (cl:cons ':result (result msg))
))
