// Generated by gencpp from file exercice_2/charge_status_req.msg
// DO NOT EDIT!


#ifndef EXERCICE_2_MESSAGE_CHARGE_STATUS_REQ_H
#define EXERCICE_2_MESSAGE_CHARGE_STATUS_REQ_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace exercice_2
{
template <class ContainerAllocator>
struct charge_status_req_
{
  typedef charge_status_req_<ContainerAllocator> Type;

  charge_status_req_()
    : id(0)  {
    }
  charge_status_req_(const ContainerAllocator& _alloc)
    : id(0)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::exercice_2::charge_status_req_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::exercice_2::charge_status_req_<ContainerAllocator> const> ConstPtr;

}; // struct charge_status_req_

typedef ::exercice_2::charge_status_req_<std::allocator<void> > charge_status_req;

typedef boost::shared_ptr< ::exercice_2::charge_status_req > charge_status_reqPtr;
typedef boost::shared_ptr< ::exercice_2::charge_status_req const> charge_status_reqConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::exercice_2::charge_status_req_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::exercice_2::charge_status_req_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::exercice_2::charge_status_req_<ContainerAllocator1> & lhs, const ::exercice_2::charge_status_req_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::exercice_2::charge_status_req_<ContainerAllocator1> & lhs, const ::exercice_2::charge_status_req_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace exercice_2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::exercice_2::charge_status_req_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exercice_2::charge_status_req_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exercice_2::charge_status_req_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exercice_2::charge_status_req_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exercice_2::charge_status_req_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exercice_2::charge_status_req_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::exercice_2::charge_status_req_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c5e4a7d59c68f74eabcec876a00216aa";
  }

  static const char* value(const ::exercice_2::charge_status_req_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc5e4a7d59c68f74eULL;
  static const uint64_t static_value2 = 0xabcec876a00216aaULL;
};

template<class ContainerAllocator>
struct DataType< ::exercice_2::charge_status_req_<ContainerAllocator> >
{
  static const char* value()
  {
    return "exercice_2/charge_status_req";
  }

  static const char* value(const ::exercice_2::charge_status_req_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::exercice_2::charge_status_req_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 id\n"
;
  }

  static const char* value(const ::exercice_2::charge_status_req_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::exercice_2::charge_status_req_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct charge_status_req_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::exercice_2::charge_status_req_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::exercice_2::charge_status_req_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXERCICE_2_MESSAGE_CHARGE_STATUS_REQ_H
