// Generated by gencpp from file exercice_2/charge_statusRequest.msg
// DO NOT EDIT!


#ifndef EXERCICE_2_MESSAGE_CHARGE_STATUSREQUEST_H
#define EXERCICE_2_MESSAGE_CHARGE_STATUSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace exercice_2
{
template <class ContainerAllocator>
struct charge_statusRequest_
{
  typedef charge_statusRequest_<ContainerAllocator> Type;

  charge_statusRequest_()
    : src_room_id(0)  {
    }
  charge_statusRequest_(const ContainerAllocator& _alloc)
    : src_room_id(0)  {
  (void)_alloc;
    }



   typedef int32_t _src_room_id_type;
  _src_room_id_type src_room_id;





  typedef boost::shared_ptr< ::exercice_2::charge_statusRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::exercice_2::charge_statusRequest_<ContainerAllocator> const> ConstPtr;

}; // struct charge_statusRequest_

typedef ::exercice_2::charge_statusRequest_<std::allocator<void> > charge_statusRequest;

typedef boost::shared_ptr< ::exercice_2::charge_statusRequest > charge_statusRequestPtr;
typedef boost::shared_ptr< ::exercice_2::charge_statusRequest const> charge_statusRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::exercice_2::charge_statusRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::exercice_2::charge_statusRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::exercice_2::charge_statusRequest_<ContainerAllocator1> & lhs, const ::exercice_2::charge_statusRequest_<ContainerAllocator2> & rhs)
{
  return lhs.src_room_id == rhs.src_room_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::exercice_2::charge_statusRequest_<ContainerAllocator1> & lhs, const ::exercice_2::charge_statusRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace exercice_2

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::exercice_2::charge_statusRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exercice_2::charge_statusRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exercice_2::charge_statusRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exercice_2::charge_statusRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exercice_2::charge_statusRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exercice_2::charge_statusRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::exercice_2::charge_statusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3590119f6008d53f50c81cd6f7fbc149";
  }

  static const char* value(const ::exercice_2::charge_statusRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3590119f6008d53fULL;
  static const uint64_t static_value2 = 0x50c81cd6f7fbc149ULL;
};

template<class ContainerAllocator>
struct DataType< ::exercice_2::charge_statusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "exercice_2/charge_statusRequest";
  }

  static const char* value(const ::exercice_2::charge_statusRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::exercice_2::charge_statusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 src_room_id\n"
;
  }

  static const char* value(const ::exercice_2::charge_statusRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::exercice_2::charge_statusRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.src_room_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct charge_statusRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::exercice_2::charge_statusRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::exercice_2::charge_statusRequest_<ContainerAllocator>& v)
  {
    s << indent << "src_room_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.src_room_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXERCICE_2_MESSAGE_CHARGE_STATUSREQUEST_H
