// Generated by gencpp from file svctest/srv1.msg
// DO NOT EDIT!


#ifndef SVCTEST_MESSAGE_SRV1_H
#define SVCTEST_MESSAGE_SRV1_H

#include <ros/service_traits.h>


#include <svctest/srv1Request.h>
#include <svctest/srv1Response.h>


namespace svctest
{

struct srv1
{

typedef srv1Request Request;
typedef srv1Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct srv1
} // namespace svctest


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::svctest::srv1 > {
  static const char* value()
  {
    return "2a5c7a37218262bae4fcfaa1007692aa";
  }

  static const char* value(const ::svctest::srv1&) { return value(); }
};

template<>
struct DataType< ::svctest::srv1 > {
  static const char* value()
  {
    return "svctest/srv1";
  }

  static const char* value(const ::svctest::srv1&) { return value(); }
};


// service_traits::MD5Sum< ::svctest::srv1Request> should match
// service_traits::MD5Sum< ::svctest::srv1 >
template<>
struct MD5Sum< ::svctest::srv1Request>
{
  static const char* value()
  {
    return MD5Sum< ::svctest::srv1 >::value();
  }
  static const char* value(const ::svctest::srv1Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::svctest::srv1Request> should match
// service_traits::DataType< ::svctest::srv1 >
template<>
struct DataType< ::svctest::srv1Request>
{
  static const char* value()
  {
    return DataType< ::svctest::srv1 >::value();
  }
  static const char* value(const ::svctest::srv1Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::svctest::srv1Response> should match
// service_traits::MD5Sum< ::svctest::srv1 >
template<>
struct MD5Sum< ::svctest::srv1Response>
{
  static const char* value()
  {
    return MD5Sum< ::svctest::srv1 >::value();
  }
  static const char* value(const ::svctest::srv1Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::svctest::srv1Response> should match
// service_traits::DataType< ::svctest::srv1 >
template<>
struct DataType< ::svctest::srv1Response>
{
  static const char* value()
  {
    return DataType< ::svctest::srv1 >::value();
  }
  static const char* value(const ::svctest::srv1Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SVCTEST_MESSAGE_SRV1_H
